### ISSUE TITLE
iteration1 - tests have errors or fail

### ISSUE THREAD

**Issue by jbrucker** [pimmimagi/ku-polls#18]
After fixing mysite/urls.py, when I run tests on your iteration1 branch
it shows these failures and errors:

Sarocha/ku-polls$ manage test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
..FF...EEE
======================================================================
ERROR: test_was_published_recently_with_future_question (polls.tests.QuestionModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Sarocha/ku-polls/polls/tests.py", line 18, in test_was_published_recently_with_future_question
    self.assertIs(future_question.was_published_recently(), False)
  File "/home/submit/ISP/Sarocha/ku-polls/polls/models.py", line 13, in was_published_recently
    return now - datetime.timedelta(days=1) <= self.pub_date <= now
NameError: name 'datetime' is not defined

======================================================================
ERROR: test_was_published_recently_with_old_question (polls.tests.QuestionModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Sarocha/ku-polls/polls/tests.py", line 27, in test_was_published_recently_with_old_question
    self.assertIs(old_question.was_published_recently(), False)
  File "/home/submit/ISP/Sarocha/ku-polls/polls/models.py", line 13, in was_published_recently
    return now - datetime.timedelta(days=1) <= self.pub_date <= now
NameError: name 'datetime' is not defined

======================================================================
ERROR: test_was_published_recently_with_recent_question (polls.tests.QuestionModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Sarocha/ku-polls/polls/tests.py", line 36, in test_was_published_recently_with_recent_question
    self.assertIs(recent_question.was_published_recently(), True)
  File "/home/submit/ISP/Sarocha/ku-polls/polls/models.py", line 13, in was_published_recently
    return now - datetime.timedelta(days=1) <= self.pub_date <= now
NameError: name 'datetime' is not defined

======================================================================
FAIL: test_future_question (polls.tests.QuestionIndexViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Sarocha/ku-polls/polls/tests.py", line 77, in test_future_question
    self.assertContains(response, "No polls are available.")
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 471, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'No polls are available.' in response

======================================================================
FAIL: test_future_question_and_past_question (polls.tests.QuestionIndexViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/submit/ISP/Sarocha/ku-polls/polls/tests.py", line 90, in test_future_question_and_past_question
    ['<Question: Past question.>']
  File "/usr/local/lib/python3.6/dist-packages/django/test/testcases.py", line 1072, in assertQuerysetEqual
    return self.assertEqual(list(items), values, msg=msg)
AssertionError: Lists differ: ['<Question: Future question.>', '<Question: Past question.>'] != ['<Question: Past question.>']

First differing element 0:
'<Question: Future question.>'
'<Question: Past question.>'

First list contains 1 additional elements.
First extra element 1:
'<Question: Past question.>'

- ['<Question: Future question.>', '<Question: Past question.>']
+ ['<Question: Past question.>']

----------------------------------------------------------------------
Ran 10 tests in 0.047s

**Comment by pimmimagi** [comment]
The problem is now solved in iteration 2
